version: "3.1"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="laguna"
    ports:
      - "27017:27017"
  mongodb-test:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - "27018:27017"