version: '3.1'

services:

  iris:
    image: iris
    container_name: iris
    restart: always
    environment:
      - NODE_ENV=localhost
    ports:
      - "3001:3001"
    volumes:
     - $HOME/.aws:/root/.aws:ro
