name: Iris

on:
  push:
    branches:
      - develop
      - staging
  pull_request:
    branches:
      - develop

jobs:
  whitesource:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Whitesource Scan
        uses: TheAxZim/Whitesource-Scan-Action@v1.0.0
        with:
          wssUrl: https://saas-eu.whitesourcesoftware.com/agent
          apiKey: ${{ secrets.WHITESOURCE_API_KEY }}
          productName: 'Backend'
          projectName: 'iris'
          
  lint:
    name: Lint
    runs-on: self-hosted
    timeout-minutes: 3
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
      - name: Install node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install yarn
        run: npm install -g yarn
      - name: Create npmrc and yarnrc files
        run: echo "//npm.pkg.github.com/:_authToken=${{secrets.NPM_PRIVATE_GITHUB_AUTH_TOKEN_REGISTRY}}" > ~/.npmrc
      - name: Install project dependencies
        run: yarn install --frozen-lockfile
      - name: Run linters
        run: yarn lint

  build-test-coverage:
    name: Build, Test and Coverage
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
      - name: Install node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install yarn
        run: npm install -g yarn
      - name: Create npmrc and yarnrc files
        run: echo "//npm.pkg.github.com/:_authToken=${{secrets.NPM_PRIVATE_GITHUB_AUTH_TOKEN_REGISTRY}}" > ~/.npmrc
      - name: Install project dependencies
        run: yarn install --frozen-lockfile
      - name: Build project
        run: yarn build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Test
        run: yarn test:cov
      - name: Zip lcov-report
        if: github.ref != 'refs/heads/poeditor'
        uses: papeloto/action-zip@v1
        with:
          files: coverage/lcov-report
          dest: coverage.zip
      - name: Upload coverage zip
        if: github.ref != 'refs/heads/poeditor'
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.zip
      - name: Remove lcov-report before uploading to S3
        if: github.ref != 'refs/heads/poeditor'
        run: |
          rm coverage.zip
          rm -rf coverage/lcov-report
      - name: Get local coverage report
        if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/staging' && github.ref != 'refs/heads/poeditor'
        id: localCoverage
        uses: notiz-dev/github-action-json-property@release
        with:
          path: './coverage/coverage-summary.json'
          prop_path: 'total.lines.pct'
      - name: Download develop coverage report from S3
        if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/staging' && github.ref != 'refs/heads/poeditor'
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: 's3://${{ secrets.COVERAGE_AWS_BUCKET }}/develop/coverage-summary.json'
          dest: './coverage/develop/coverage-summary.json'
      - name: Get develop coverage report
        if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/staging' && github.ref != 'refs/heads/poeditor'
        id: developCoverage
        uses: notiz-dev/github-action-json-property@release
        with:
          path: './coverage/develop/coverage-summary.json'
          prop_path: 'total.lines.pct'
      - name: Set coverage diff
        if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/staging' && github.ref != 'refs/heads/poeditor'
        run: echo "DIFF_COV=$(echo "${{steps.localCoverage.outputs.prop}}-${{steps.developCoverage.outputs.prop}}" | bc)" >> $GITHUB_ENV
      - name: Add coverage report url and diff to PR
        if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/staging' && github.ref != 'refs/heads/poeditor'
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            ### coverage report for `${{ github.head_ref }}` -> `develop`
            ___
            | **Total** | **${{steps.localCoverage.outputs.prop}}% (${{ env.DIFF_COV }}%)** | **[lcov report](https://github.com/LagunaHealth/iris/actions/runs/${{ github.run_id }})** |
            |-----------|-------------------------------------------------------------------|---------------------------------------------------------------------------------------------|
          allow-repeats: false
      - name: Remove develop coverage from S3 if exists
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        uses: vitorsgomes/s3-rm-action@master
        with:
          args: --recursive
        env:
          AWS_S3_BUCKET: ${{ secrets.COVERAGE_AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.COVERAGE_AWS_REGION }}
          PATH_TO_DELETE: 'develop'
      - name: Upload develop coverage to S3
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.COVERAGE_AWS_BUCKET }}
          source_dir: './coverage'
          destination_dir: 'develop'

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: build-test-coverage
    timeout-minutes: 30
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging'

    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: Accumulate NODE_ENV
        id: branch_check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ steps.branch-name.outputs.current_branch }}" = "staging" ]; then
            echo "::set-output name=env_name::production"
          elif [ "${{ steps.branch-name.outputs.current_branch }}" = "develop" ]; then
            echo "::set-output name=env_name::development"
          fi
      - name: Log environment vars
        run: |
          echo "current branch=${{ steps.branch-name.outputs.current_branch }}"
          echo "current env_name=${{ steps.branch_check.outputs.env_name }}"
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: iris-${{ steps.branch-name.outputs.current_branch }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . --build-arg NPM_TOKEN=${{ secrets.NPM_PRIVATE_GITHUB_AUTH_TOKEN_REGISTRY }} --build-arg GIT_COMMIT=${{ github.sha }} --build-arg NODE_ENV=${{ steps.branch_check.outputs.env_name }}
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition fargate-task-iris-${{ steps.branch-name.outputs.current_branch }} \
          --query taskDefinition > task-definition.json
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: iris-${{ steps.branch-name.outputs.current_branch }}-container
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: iris-${{ steps.branch-name.outputs.current_branch }}-service
          cluster: cluster-hepius-${{ steps.branch-name.outputs.current_branch }}
          wait-for-service-stability: true

      - name: Notify deploy to Slack
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.SLACK_URL_MESSAGES }}
          method: 'POST'
          data: '{"username":"LagunaBot","icon_emoji":":Gear:","channel":"#ci-cd","attachments":[{"color":"#9733EE","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"*iris was deployed successfully to `${{ steps.branch-name.outputs.current_branch }}`.*\n*Last commit hash `${{ github.sha }}`*\nhttps://github.com/LagunaHealth/iris/actions/runs/${{ github.run_id }}"}}]}]}'
