name: Trigger generating analytics

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  load-analytics-to-sql:
    name: Loadinging analytics data to sql db
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: Install node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: staging
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        run: yarn install
      - name: Export Analytics
        run: |
          su - ec2-user
          yarn analytics:dump:prod
